export interface BaseAction {
  type: string;
  payload?: any;
}

export const actionIds = {
  GET_GIT_COMMIT_LOG: 'GET_GIT_COMMIT_LOG',
  GET_GIT_COMMIT_LOG_COMPLETED: 'GET_GIT_COMMIT_LOG_COMPLETED',
  LOAD_NEW_GIT_DIFF: 'LOAD_NEW_GIT_DIFF',
  LOAD_NEW_GIT_DIFF_COMPLETED: 'LOAD_NEW_GIT_DIFF_COMPLETED',
  LOAD_NEW_GIT_JSON: 'LOAD_NEW_GIT_JSON',
  LOAD_NEW_GIT_JSON_COMPLETED: 'LOAD_NEW_GIT_JSON_COMPLETED',
  CHANGE_DIRECTORY: 'CHANGE_DIRECTORY',
};
